export { AboutMe } from './AboutMe'
export { Footer } from './Footer'
export { Hero } from './Hero'
export { SoftSkills } from './SoftSkills'
export { RecentProjects } from './RecentProjects'
export { TechStack } from './TechStack'
export { Testimonials } from './Testimonials'
